### ISSUE TITLE
Code of GenAD

### ISSUE THREAD

**Issue by JarveeLee** [OpenDriveLab/DriveAGI#13]
Do you plan to release the training, inference code of GenAD along with data processing scripts ?

**Comment by Little-Podi** [comment]
Thanks for your interest. We have developed an upgraded version based on OpenDV and GenAD. The paper, the code and the model will be made available later this month. Please stay tuned for our updates.
For data processing scripts, we recommend referring to follow the process in the Appendix of GenAD. It should be straightforward to replicate similar results.

**Comment by Little-Podi** [comment]
Hi there, please check our new work at https://arxiv.org/abs/2405.17398 and https://github.com/OpenDriveLab/Vista

**Comment by JarveeLee** [comment]
Amazing !
