### ISSUE TITLE
mini-dataset-extract error

### ISSUE THREAD

**Issue by zhoujiawei3** [OpenDriveLab/DriveAGI#20]
[NULL @ 0x25177c0] Invalid NAL unit size (2052818445 > 4717).
[NULL @ 0x25177c0] missing picture in access unit with size 4721
[NULL @ 0x25177c0] Invalid NAL unit size (-396223407 > 15374).
[NULL @ 0x25177c0] missing picture in access unit with size 15378
[h264 @ 0x2859940] Invalid NAL unit size (2052818445 > 4717).
[h264 @ 0x2859940] Error splitting the input into NAL units.
[NULL @ 0x25177c0] Invalid NAL unit size (-266338098 > 2926).
[NULL @ 0x25177c0] missing picture in access unit with size 2930
[h264 @ 0x28c3a40] Invalid NAL unit size (-396223407 > 15374).
[h264 @ 0x28c3a40] Error splitting the input into NAL units.
[h264 @ 0x29019c0] cabac decode of qscale diff failed at 40 7
[h264 @ 0x29019c0] error while decoding MB 40 7, bytestream 15264
[NULL @ 0x25177c0] Invalid NAL unit size (585729619 > 14809).
[NULL @ 0x25177c0] missing picture in access unit with size 14813
[h264 @ 0x288ff00] Invalid NAL unit size (-266338098 > 2926).
[h264 @ 0x288ff00] Error splitting the input into NAL units.
[NULL @ 0x25177c0] Invalid NAL unit size (-1066979484 > 3160).
[NULL @ 0x25177c0] missing picture in access unit with size 3164
[h264 @ 0x2916040] Invalid NAL unit size (585729619 > 14809).
[h264 @ 0x2916040] Error splitting the input into NAL units.
[h264 @ 0x29529c0] Invalid NAL unit size (-1066979484 > 3160).
[h264 @ 0x29529c0] Error splitting the input into NAL units.
[NULL @ 0x25177c0] Invalid NAL unit size (1001892041 > 15783).
[NULL @ 0x25177c0] missing picture in access unit with size 15787
[NULL @ 0x25177c0] Invalid NAL unit size (1427248101 > 3127).
[NULL @ 0x25177c0] missing picture in access unit with size 3131
[h264 @ 0x2966d80] Invalid NAL unit size (1001892041 > 15783).
[h264 @ 0x2966d80] Error splitting the input into NAL units.
[h264 @ 0x320aa00] Invalid NAL unit size (1427248101 > 3127).
[h264 @ 0x320aa00] Error splitting the input into NAL units.
[NULL @ 0x25177c0] Invalid NAL unit size (-1770211463 > 28753).
[NULL @ 0x25177c0] missing picture in access unit with size 28757
[NULL @ 0x25177c0] Invalid NAL unit size (-196288894 > 5149).
[NULL @ 0x25177c0] missing picture in access unit with size 5153
[h264 @ 0x32d98c0] Invalid NAL unit size (-1770211463 > 28753).
[h264 @ 0x32d98c0] Error splitting the input into NAL units.
[NULL @ 0x25177c0] Invalid NAL unit size (379760075 > 4690).
[NULL @ 0x25177c0] missing picture in access unit with size 4694
[h264 @ 0x33a8980] Invalid NAL unit size (-196288894 > 5149).
[h264 @ 0x33a8980] Error splitting the input into NAL units.
[h264 @ 0x3477a40] Invalid NAL unit size (379760075 > 4690).
[h264 @ 0x3477a40] Error splitting the input into NAL units.
[NULL @ 0x25177c0] Invalid NAL unit size (-1351246022 > 16721).
[NULL @ 0x25177c0] missing picture in access unit with size 16725
[NULL @ 0x25177c0] Invalid NAL unit size (-500527169 > 43639).
[NULL @ 0x25177c0] missing picture in access unit with size 43643
[h264 @ 0x3546c80] Invalid NAL unit size (-1351246022 > 16721).
[h264 @ 0x3546c80] Error splitting the input into NAL units.
[h264 @ 0x3615f00] Invalid NAL unit size (-500527169 > 43639).
[h264 @ 0x3615f00] Error splitting the input into NAL units.
[NULL @ 0x25177c0] Invalid NAL unit size (-2087808550 > 4439).
[NULL @ 0x25177c0] missing picture in access unit with size 4443
[h264 @ 0x2869e40] Invalid NAL unit size (-2087808550 > 4439).
[h264 @ 0x2869e40] Error splitting the input into NAL units.
[NULL @ 0x25177c0] Invalid NAL unit size (1086282545 > 5340).
[NULL @ 0x25177c0] missing picture in access unit with size 5344
[h264 @ 0x28d3680] Invalid NAL unit size (1086282545 > 5340).
[h264 @ 0x28d3680] Error splitting the input into NAL units.
[NULL @ 0x25177c0] Invalid NAL unit size (753367453 > 26184).
[NULL @ 0x25177c0] missing picture in access unit with size 26188
[h264 @ 0x28652c0] Invalid NAL unit size (753367453 > 26184).
[h264 @ 0x28652c0] Error splitting the input into NAL units.
[NULL @ 0x25177c0] Invalid NAL unit size (38121706 > 4201).
[NULL @ 0x25177c0] missing picture in access unit with size 4205
[NULL @ 0x25177c0] Invalid NAL unit size (1328611328 > 4267).
[NULL @ 0x25177c0] missing picture in access unit with size 4271
[h264 @ 0x29019c0] Invalid NAL unit size (38121706 > 4201).
[h264 @ 0x29019c0] Error splitting the input into NAL units.
[h264 @ 0x2859940] Invalid NAL unit size (1328611328 > 4267).
[h264 @ 0x2859940] Error splitting the input into NAL units.
Traceback (most recent call last):
  File "/data2/zhoujiawei/DriveAGI/opendv/utils/frame_extraction.py", line 43, in extract_frames
    cv2_extract_frames(video_path, output_dir, fps, discard_begin, discard_end, exception_file)
  File "/data2/zhoujiawei/DriveAGI/opendv/utils/frame_extraction.py", line 178, in cv2_extract_frames
    cv2.imwrite(file_path, frame)
cv2.error: OpenCV(4.10.0) /io/opencv/modules/imgcodecs/src/loadsave.cpp:798: error: (-215:Assertion failed) !_img.empty() in function 'imwrite'

This occur and the extraction is stuck, what should I do?

**Comment by zhoujiawei3** [comment]
I follow the readme step by step on another machine. The problem occurs again
[av1 @ 0xff7b00] Your platform doesn't suppport hardware accelerated AV1 decoding.
[av1 @ 0xff7b00] Failed to get pixel format.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Your platform doesn't suppport hardware accelerated AV1 decoding.
[av1 @ 0xff7b00] Failed to get pixel format.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xff7b00] Missing Sequence Header.
[av1 @ 0xf38ac0] Your platform doesn't suppport hardware accelerated AV1 decoding.
[av1 @ 0xf38ac0] Failed to get pixel format.
[av1 @ 0xf38ac0] Your platform doesn't suppport hardware accelerated AV1 decoding.
[av1 @ 0xf38ac0] Failed to get pixel format.
[av1 @ 0xf38ac0] Your platform doesn't suppport hardware accelerated AV1 decoding.
[av1 @ 0xf38ac0] Failed to get pixel format.
[av1 @ 0xf38ac0] Your platform doesn't suppport hardware accelerated AV1 decoding.
[av1 @ 0xf38ac0] Failed to get pixel format.
[av1 @ 0xf38ac0] Your platform doesn't suppport hardware accelerated AV1 decoding.
[av1 @ 0xf38ac0] Failed to get pixel format.
[av1 @ 0xf38ac0] Your platform doesn't suppport hardware accelerated AV1 decoding.
[av1 @ 0xf38ac0] Failed to get pixel format.
[av1 @ 0xf38ac0] Your platform doesn't suppport hardware accelerated AV1 decoding.
[av1 @ 0xf38ac0] Failed to get pixel format.
[av1 @ 0xf38ac0] Your platform doesn't suppport hardware accelerated AV1 decoding.
[av1 @ 0xf38ac0] Failed to get pixel format.
[av1 @ 0xf38ac0] Your platform doesn't suppport hardware accelerated AV1 decoding.
[av1 @ 0xf38ac0] Failed to get pixel format.
[av1 @ 0xf38ac0] Your platform doesn't suppport hardware accelerated AV1 decoding.
[av1 @ 0xf38ac0] Failed to get pixel format.
[av1 @ 0xf38ac0] Your platform doesn't suppport hardware accelerated AV1 decoding.
[av1 @ 0xf38ac0] Failed to get pixel format.
[av1 @ 0xf38ac0] Your platform doesn't suppport hardware accelerated AV1 decoding.
[av1 @ 0xf38ac0] Failed to get pixel format.
[av1 @ 0xf38ac0] Your platform doesn't suppport hardware accelerated AV1 decoding.
[av1 @ 0xf38ac0] Failed to get pixel format.
[av1 @ 0xf38ac0] Your platform doesn't suppport hardware accelerated AV1 decoding.
[av1 @ 0xf38ac0] Failed to get pixel format.
[av1 @ 0xf38ac0] Your platform doesn't suppport hardware accelerated AV1 decoding.
[av1 @ 0xf38ac0] Failed to get pixel format.
[av1 @ 0xf38ac0] Your platform doesn't suppport hardware accelerated AV1 decoding.
[av1 @ 0xf38ac0] Failed to get pixel format.
[av1 @ 0xf38ac0] Your platform doesn't suppport hardware accelerated AV1 decoding.
[av1 @ 0xf38ac0] Failed to get pixel format.
[av1 @ 0xf38ac0] Missing Sequence Header.
Traceback (most recent call last):
  File "/ENS/zjw/DriveAGI/opendv/utils/frame_extraction.py", line 43, in extract_frames
    cv2_extract_frames(video_path, output_dir, fps, discard_begin, discard_end, exception_file)
  File "/ENS/zjw/DriveAGI/opendv/utils/frame_extraction.py", line 175, in cv2_extract_frames
    cv2.imwrite(file_path, frame)
cv2.error: OpenCV(4.10.0) /io/opencv/modules/imgcodecs/src/loadsave.cpp:798: error: (-215:Asserti
on failed) !_img.empty() in function 'imwrite'

what should I do?

**Comment by GihhArwtw** [comment]
hi @zhoujiawei3 

yes, i think the error is related to unsuccessful download. Maybe you could try to use another tool to download videos of KenoVelicanstveni‘s videos? You just need to change [`method`](https://github.com/OpenDriveLab/DriveAGI/blob/main/opendv/configs/download.json#L4) in `configs/download.json` to `yt-dlp`.

**Comment by zhoujiawei3** [comment]
@GihhArwtw  I have already changed to yt-dlp, as the other method doesn't work for me. I try several times to download the mini-dataset on different machines, the problem occurs on the same video KenoVelicanstveni/Qb5UT3pSxjI.mp4. And I have checked they are both 2,56,1,588,623 B. When I remove that video and adjust the json, the video2img.py can successfully run.

**Comment by zhoujiawei3** [comment]
@GihhArwtw But only extract two val video ：（. Is that right? For images to train, don't we need to change it to images? 
![image](https://github.com/user-attachments/assets/3264f443-02bd-4bf6-ba70-00adef6500ef)

**Comment by GihhArwtw** [comment]
no it's not right. I think it's used for debugging and I forgot to comment it out when pushing the code. Thanks for pointing this out.

**Comment by GihhArwtw** [comment]
already fixed and updated :)

**Comment by zhoujiawei3** [comment]
@GihhArwtw Thank you for your reply. However, after I made the changes here and tried to extract again, all the mp4 videos in the train set encountered an ffmpeg-related issue. None of the mp4 videos could be extracted, and an error appeared. Since the downloaded exception.txt shows "Checking download status finished" and the video size remains the same despite multiple attempts to download, I suspect this may not be a download issue. Could it be that ffmpeg and mp4 are incompatible, as mentioned in the tutorial? I'm not sure how to resolve this problem. I would greatly appreciate any help you could provide.

**Comment by GihhArwtw** [comment]
I'll check on it.
But in fact `ffmpeg` is used only for checking the download status and we use `opencv` for frame extraction, I think there might be some other problems.

**Comment by GihhArwtw** [comment]
hi @zhoujiawei3
i still need to confirm one more thing with you, though. On our server, some videos downloaded by `yt-dlp` are of `webm` format and renaming them to `mp4` has caused problems before. 
For example, the video `KenoVelicanstveni/Qb5UT3pSxjI` is downloaded in `webm` format on our server. But according to your feedback above, it is downloaded as `mp4` format on your server.
So i'm wondering whether this is caused by different python version or something like that. Could you please provide more info, e.g. system (Linux/Windows), conda env and installed packages?

**Comment by zhoujiawei3** [comment]
My system is Linux.
![image](https://github.com/user-attachments/assets/413b85da-8de7-44e3-8062-8ba863e7aee6)
 I'm not quite sure what format the video is in during the download process, but after it's completed, it's in MP4 format. 
![image](https://github.com/user-attachments/assets/368f2250-94e7-4760-bdf3-f4087ca82d20)
![image](https://github.com/user-attachments/assets/cc9c2998-5dfc-4bd0-8463-01a7c7d18e9e)
![image](https://github.com/user-attachments/assets/76f0dc2d-71f2-4801-a005-2efd162e43a3)
I notice this difference, the 'mp4' format videos don't have '*.mp4.part' file in the folder, while the 'webm' format video has it in the folder.

**Comment by GihhArwtw** [comment]
get it. 
I noticed that you are using `yt-dlp==2024.11.4`, which is different from that in our env (`yt-dlp==2024.8.6`). I'm not sure if this caused the problem but I'll check on it.

![image](https://github.com/user-attachments/assets/d6bc2016-5d8b-4e9b-89b7-5ada4175f6be)

**Comment by zhoujiawei3** [comment]
My download process don't have been interrupted manually. I suspect that perhaps the initial download failed when using multiple workers, and some fragment files were not deleted properly? I try to download the video on another server, *.part and *.ytdl don‘t exist in the final folder, as your words. I compared the sizes of the downloaded MP4 and WEBM files on these two server, they are identical. I guess the mp4 file occuring problem isn't related to the unsuccessful download. Maybe it's related to the version of yt-dlp,  I will try it, thank you！

**Comment by GihhArwtw** [comment]
in the meantime I'm running the scripts completely  from scratch on our server. If I found other problems, I'll keep you updated.

**Comment by GihhArwtw** [comment]
the mini subbset download just finished on our test server. I test the `video2img` script and it works well. I suppose the problem is caused by the version of `yt-dlp` indeed.
Please let us know if you encounter other issues in the following process. I'll update the `requirements.txt` once `yt-dlp==2024.8.6` works well on your end.

**Comment by zhoujiawei3** [comment]
When I change yt-dlp==2024.8.6, the problem is solved. Thank you for your help!

**Comment by GihhArwtw** [comment]
also updated in requirements. Hope everything goes well!
